### ISSUE TITLE
Handsontable

### ISSUE THREAD

**Issue by BDalheimer** [SWS-Methodology/shinyFBS#3]
Currently, the rhandsontable package is in use for displaying the SUA element tables and for inputting data. However, there is a problem using data.table since the tables are completely messed up once `useType = T`, which would allow numeric instead of logical number format. Other table options are the reglar hot_tables or D3TableFilter

**Comment by marcosmilzo** [comment]
Just a comment: let's make sure to load the rhandsotables from github, in case package already installed from CRAN
